
USE LuresGalore;

ALTER TABLE Product
WITH CHECK ADD  CONSTRAINT FK_Product_Price
FOREIGN KEY(PriceId)
REFERENCES Price(PriceId);
GO

ALTER TABLE [dbo].Product CHECK CONSTRAINT FK_Product_Price;
GO

ALTER TABLE "User"
WITH CHECK ADD CONSTRAINT FK_USER_ROLE
FOREIGN KEY(RoleId)
REFERENCES Role (RoleId);
GO

ALTER TABLE [dbo]."User" CHECK CONSTRAINT FK_USER_ROLE;
GO


ALTER TABLE ShoppingCart
WITH CHECK ADD CONSTRAINT FK_SC_USER
FOREIGN KEY (UserId)
REFERENCES "User"(UserID);
GO

ALTER TABLE [dbo].ShoppingCart CHECK CONSTRAINT FK_SC_USER;
GO


ALTER TABLE "Order"
WITH CHECK ADD CONSTRAINT FK_ORDER_USER
FOREIGN KEY (UserId)
REFERENCES "User"(UserId);
GO

ALTER TABLE [dbo]."Order" CHECK CONSTRAINT FK_ORDER_USER;
GO


ALTER TABLE ProductCategory
WITH CHECK ADD CONSTRAINT FK_PC_ProdID
FOREIGN KEY (ProductId)
REFERENCES Product(ProductId);
GO

ALTER TABLE [dbo].ProductCategory CHECK CONSTRAINT FK_PC_ProdID;
GO


ALTER TABLE ProductCategory
WITH CHECK ADD CONSTRAINT FK_PC_CAT
FOREIGN KEY (CategoryId)
REFERENCES Category(CategoryID);
GO

ALTER TABLE [dbo].ProductCategory CHECK CONSTRAINT FK_PC_CAT;
GO


ALTER TABLE  ShoppingCartLineItem
WITH CHECK ADD CONSTRAINT  FK_SCLI_SC
FOREIGN KEY (ShoppingCartId)
REFERENCES ShoppingCart(ShoppingCartId);
GO

ALTER TABLE [dbo].ShoppingCartLineItem CHECK CONSTRAINT FK_SCLI_SC;
GO


ALTER TABLE  ShoppingCartLineItem
WITH CHECK ADD CONSTRAINT  FK_SHLI_LI
FOREIGN KEY (LineItemId)
REFERENCES LineItem(LineItemId);
GO

ALTER TABLE [dbo].ShoppingCartLineItem CHECK CONSTRAINT FK_SHLI_LI;
GO


ALTER TABLE OrderLineItem
WITH CHECK ADD CONSTRAINT FK_OLI_Order
FOREIGN KEY(OrderId)
REFERENCES "Order"(OrderId);
GO

ALTER TABLE [dbo].OrderLineItem CHECK CONSTRAINT FK_OLI_Order;
GO


ALTER TABLE OrderLineItem
WITH CHECK ADD CONSTRAINT FK_OLI_LineItem
FOREIGN KEY (LineItemId)
REFERENCES LineItem(LineItemId);
GO

ALTER TABLE [dbo].OrderLineItem CHECK CONSTRAINT FK_OLI_LineItem;
GO


ALTER TABLE LineItem
WITH CHECK ADD CONSTRAINT FK_LineItem_Product
FOREIGN KEY (ProductId)
REFERENCES Product(ProductId);
GO

ALTER TABLE [dbo].LineItem CHECK CONSTRAINT FK_LineItem_Product;
GO












