
USE LuresGalore;


ALTER TABLE Product
WITH CHECK ADD  CONSTRAINT FK_Product_Price
FOREIGN KEY(PriceId)
REFERENCES Price(PriceId);

ALTER TABLE "User"
WITH CHECK ADD CONSTRAINT FK_USER_ROLE
FOREIGN KEY(RoleId)
REFERENCES Role (RoleId);

ALTER TABLE ShoppingCart
WITH CHECK ADD CONSTRAINT FK_SC_USER
FOREIGN KEY (UserId)
REFERENCES "User"(UserID);

ALTER TABLE "Order"
WITH CHECK ADD CONSTRAINT FK_ORDER_USER
FOREIGN KEY (UserId)
REFERENCES "User"(UserId);

ALTER TABLE ProductCategory
WITH CHECK ADD CONSTRAINT FK_PC_ProdID
FOREIGN KEY (ProductId)
REFERENCES Product(ProductId);
Go

ALTER TABLE ProductCategory
WITH CHECK ADD CONSTRAINT FK_PC_CAT
FOREIGN KEY (CategoryId)
REFERENCES Category(CategoryID);

ALTER TABLE  ShoppingCartLineItem
WITH CHECK ADD CONSTRAINT  FK_SCLI_SC
FOREIGN KEY (ShoppingCartId)
REFERENCES ShoppingCart(ShoppingCartId)

ALTER TABLE  ShoppingCartLineItem
WITH CHECK ADD CONSTRAINT  FK_SHLI_LI
FOREIGN KEY (LineItemId)
REFERENCES LineItem(LineItemId);

ALTER TABLE OrderLineItem
WITH CHECK ADD CONSTRAINT FK_OLI_Order
FOREIGN KEY(OrderId)
REFERENCES "Order"(OrderId);

ALTER TABLE OrderLineItem
WITH CHECK ADD CONSTRAINT FK_OLI_LineItem
FOREIGN KEY (LineItemId)
REFERENCES LineItem(LineItemId)

ALTER TABLE LineItem
WITH CHECK ADD CONSTRAINT FK_LineItem_Product
FOREIGN KEY (ProductId)
REFERENCES Product(ProductId);
GO










